### ISSUE TITLE
chore: add copilot instructions based on CI

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#1905]
use the existing CI to write copilot startup instructions.

follow the official guide found on github

here's an example of something close to what we want

```
name: "Copilot Setup Steps"

# Allow testing of the setup steps from your repository's "Actions" tab.
on: workflow_dispatch

jobs:
  # The job MUST be called `copilot-setup-steps` or it will not be picked up by Copilot.
  copilot-setup-steps:
    runs-on: ubuntu-latest

    # Set the permissions to the lowest permissions possible needed for your steps.
    # Copilot will be given its own token for its operations.
    permissions:
      # If you want to clone the repository as part of your setup steps, for example to install dependencies, you'll need the `contents: read` permission. If you don't clone the repository in your setup steps, Copilot will do this for you automatically after the steps complete.
      contents: read

    # You can define any steps you want, and they will run before the agent starts.
    # If you do not check out your code, Copilot will do this for you.
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Cache Go binaries
        uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-binary-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-binary-
      - name: Download Go dependencies
        run: go mod download

      - name: Verify Go setup
        run: go version
```

that yml file needs to go in .github/copilot-setup-steps.yml
