### ISSUE TITLE
Decide on the default max transaction size accepted by the mempool

### ISSUE THREAD

**Issue by evan-forbes** [celestiaorg/celestia-core#867]
We want to consider changing the default config for the mempool to accept larger transactions. 

https://github.com/celestiaorg/celestia-core/blob/094cd2c631a5b970ce89e04a81f404c99c38bdf8/config/config.go#L744

related to #243 

and there are concerns as well https://github.com/celestiaorg/celestia-core/issues/243#issuecomment-804273440 https://github.com/informalsystems/audit-celestia/issues/6

**Comment by musalbas** [comment]
Can potential DoS vectors be fixed by somehow rate limiting transactions by IP or blacklisting IPs that repeatedly send invalid transactions?

**Comment by evan-forbes** [comment]
yeah that makes sense, and is likely something we will need to build in the future. afaiu this would require some significant changes to the p2p stack. I believe this is actually something that the tendermint v0.35 p2p stack was attempting to address.

**Comment by adlerjohn** [comment]
This isn't really a _DoS_ vector (it's still a _DDoS_ vector, but those are unavoidable) since the cost of validating even a large transaction really isn't that much, and a blacklist would be applied swiftly. Of course, this means we need a blacklist on invalid transactions, but that's needed anyways. Each invalid transaction can only consume a bounded amount of resources for finite time.

**Comment by musalbas** [comment]
The point is that right now I don't think there's a blacklist, and also the problem is not just with _invalid_ transactions, but with valid but very low/zero fee transactions.

**Comment by evan-forbes** [comment]
> afaiu this would require some significant changes to the p2p stack

after doing further digging, the state sync reactor has some form of peer blacklist 
https://github.com/celestiaorg/celestia-core/blob/094cd2c631a5b970ce89e04a81f404c99c38bdf8/statesync/snapshots.go#L54

other reactors do not have this afaik, but it doesn't look that hard to do when we don't generalize it across reactors

**Comment by rootulp** [comment]
I may be echoing what @adlerjohn said above but it seems like there are two separate issues being discussed here:
1. Decide on a value for `MaxTxBytes`
2. Design and implement a peer blacklist mechanism for the mempool

I think the issues are distinct and we need to reach consensus on (1) and can punt (2) until later. It also seems like (2) shouldn't impact (1) because an attacker could construct several small transactions or one large transaction. Peers of the validator can be forced to check the validity of the several small transactions or one large transaction so (2) is desirable regardless of what we decide for (1).

> The point is that right now I don't think there's a blacklist, and also the problem is not just with invalid transactions, but with valid but very low/zero fee transactions.

If we are concerned about the mempool being flooded with low/zero fee transactions, a naive mitigation to this is to implement tx prioritization https://github.com/celestiaorg/celestia-app/issues/513#issuecomment-1282984922 and then configure either or both of these mempool parameters (both default to 0):

```toml
# ttl-duration, if non-zero, defines the maximum amount of time a transaction
# can exist for in the mempool.
#
# Note, if ttl-num-blocks is also defined, a transaction will be removed if it
# has existed in the mempool at least ttl-num-blocks number of blocks or if it's
# insertion time into the mempool is beyond ttl-duration.
ttl-duration = 0

# ttl-num-blocks, if non-zero, defines the maximum number of blocks a transaction
# can exist for in the mempool.
#
# Note, if ttl-duration is also defined, a transaction will be removed if it
# has existed in the mempool at least ttl-num-blocks number of blocks or if
# it's insertion time into the mempool is beyond ttl-duration.
ttl-num-blocks = 0
```
